import { Inter } from "next/font/google";
import { Kodchasan } from 'next/font/google'

import "./styles/reset.css"
import "./globals.css";
import "./styles/pagePattern.css"

const kodchasan = Kodchasan ({
  subsets: ['latin'],
  variable: '--font-kodchasan',
  weight: '400'
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kodchasan.className}>{children}</body>
    </html>
  );
}
